[package]
name = "rs-midi-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chrono = "0.4"

midly = "0.5"
enigo = { path = "src/enigo" }
anyhow = "1"

eframe = "0.19"
egui_file = "0.3"
tokio = { version = "1", features = ["full"] }


#[[bin]]
#name = "demo"
#path = "src/demo.rs"

[[bin]]
name = "player"
path = "src/player.rs"